### ISSUE TITLE
White fluent design icons?

### ISSUE THREAD

**Issue by haverdaden** [BiGilSoft/WindowTop#101]
Hi! 

I really like the application and just bought a license. 
I do have one request though. Would it be possible to add alternative white icons with fluent design?

I was thinking about something like this: https://github.com/microsoft/fluentui-system-icons

Cheers!

**Comment by gileli121** [comment]
Hi, this is a good idea.
What do you think about the icons here:
https://github.com/gileli121/WindowTop/issues/65 
?

**Comment by haverdaden** [comment]
Yes somethink like that would look great. If possible, the tray/app icon could also have a white simple design as an alternative.

**Comment by gileli121** [comment]
@haverdaden 
Hi, I am working on it now as part of branch `v5.5`

**Comment by gileli121** [comment]
@haverdaden 
Please see the new screenshots in 
New icons #65

And respond there.
Let me know what you think about the new themes

**Comment by gileli121** [comment]
Released in v5.5
