### ISSUE TITLE
Windows Defender (Windows 10) blocks it as Malware!

### ISSUE THREAD

**Issue by adeelakramkhan** [BiGilSoft/WindowTop#102]
The latest build 5.3.0 is detected by Windows Defender as malware (Due to its registry modification to start with windows) 
![image](https://user-images.githubusercontent.com/24623243/119868700-d191d000-bf38-11eb-9a9e-2ecd485423cf.png)

**Comment by gileli121** [comment]
@adeelakramkhan 
Thanks for the report.
I submitted "Incorrect detection" report to Microsoft

I hope that they will fix it soon.

**Comment by gileli121** [comment]
@adeelakramkhan 
Software is now also released to Microsoft Store.
You should no longer get this issue with the UWP version.
You can download from here:
[ms-windows-store://pdp/?ProductId=9PG6GHB4CT57
](ms-windows-store://pdp/?ProductId=9PG6GHB4CT57)
