### ISSUE TITLE
Needs Reactivate after updating Firmware

### ISSUE THREAD

**Issue by WZ-Tong** [BiGilSoft/WindowTop#107]
Upgrade: Lenovo Firmware
Seems the firmware update changed some data in bios

**Comment by gileli121** [comment]
Same as 
https://github.com/BiGilSoft/WindowTop/issues/88

**Comment by gileli121** [comment]
@WZ-Tong 

If you want, you can test the build I posted here:
https://github.com/BiGilSoft/WindowTop/issues/134 

It comes with the option to reset the key

**Comment by gileli121** [comment]
Closed because there is a workaround now that is built-in in the software.
