### ISSUE TITLE
Can this software make a Window Always-on-Top (Original title: 请问是否能实现始终置顶功能 )

### ISSUE THREAD

**Issue by yuzlxt** [BiGilSoft/WindowTop#118]
你好，我下载这个软件是为了实现将窗口始终置顶。
我有两个显示器，一个用来看视频，一个用来工作。
我习惯使用win+d显示桌面，但是这样第二个屏幕上的视频也会最小化。
下载这个软件之后，我刚开始使用置顶的时候，可以始终置顶，第二个屏幕不受显示桌面影响。
但是之后突然又不能用了。
我想请问一下，软件本身支持始终置顶功能吗？还是我的软件出现了bug.
谢谢。

**EDIT - Translation (Thanks for Dwhite Reeves for the translation):**
His title: Can this software make a Window Always-on-Top?
1. He has Dual Screen
2. He wants to make a Window Always-on-Top on the secondary monitor even when he presses the shortcut ("Win + D") on the primary monitor. 
Vice versa
3. He said that it worked before, but now it doesn't work.

**Comment by yuzlxt** [comment]
Hello, I downloaded this software in order to achieve the window always at the top.

I have two monitors, one for watching video and one for working.

I like to use Win + D to display the desktop, but this minimizes the video on the second screen as well.

After downloading this software, when I first started using the top, I could always put the top, and the second screen was not affected by the display desktop.

But then all of a sudden it doesn't work.

I would like to ask, does the software itself support always top function? Or there's a bug in my software.

thank you！

**Comment by tuchit** [comment]
你在使用哪个版本，是最新版的吗？以及Windows系统版本呢？

**Comment by gileli121** [comment]
@yuzlxt 
Are you sure that the issue (that I am not sure I understand) happens when WindowTop is running?
WindowTop does not modify any registry key or windows settings so the is no way that it caused by WindowTop when it is not running

**Comment by gileli121** [comment]
Issue translated.
My question from 
https://github.com/BiGilSoft/WindowTop/issues/118#issuecomment-874447599
Still valid.
I will also check it myself when I will connect the computer to 2 monitors
