### ISSUE TITLE
Window state restored when changing between desktops 

### ISSUE THREAD

**Issue by JaasielCR** [BiGilSoft/WindowTop#128]
When you create a new desktop on your computer I mean whit ctrl+windows+D, and you set in top whatever window in the first desktop, **when you change to desktop 2 and return**, that window just isnt configure to be on top, you need to activate it again to be on top.

**Comment by gileli121** [comment]
@JaasielCR 
Thanks for the report.
I was able to reproduce the issue.

I will work on fix soon.

**Comment by JaasielCR** [comment]
Hi @gileli121 

I already tried the new build and it looks that the issue was solved and also stable. Fixing that it also solved another issue that i had when minimized some zoom meeting while being on top.

But now i see another kind of bug when i change between desktops and i leave one window on top and return to that desktop, of course now it still on top, but when u dragged it the red boder appear and it doesnt move with the window just sill there floating in the nothing and to hide it you need to minimize the window and change again between desktops. 

I hope you could check that, but im impressive and gratefull on how u fixed my problem.

Thanks and congrats.

**Comment by gileli121** [comment]
@JaasielCR 
Great that it fixed for you.

About the new issue, I can't reproduce it.
I tried these steps:

1. Set window on top with a red border
2. Switch to to another desktop
3. Go back to the first desktop
4. Drag the window

The red border did move with the window.
So maybe I am missing something.
Can you describe exactly the steps you did?

**Comment by JaasielCR** [comment]
Yeah of course

Maybe is also a misunderstanding, im not sure what you mean with "set on top with a red border", is it different that just "set it in top normal"? because i just set it in top like any other window, and there is no red border, but then when i do the steps 2,3 and 4 that you did the window suddenly appear with a red border and when continue dragging it the border still all the time in the orginial place of the window, it doesnt move with it. 

To be more specific these are my steps:

1. Set window on top (and there is no red border visible in this point)
2. Switch to to another desktop
3. Go back to the first desktop
4. Drag the window
5. (At this point is when the red border suddenly appear and it also stays in the place that i set the window on top, it doesnt move with the window)


I think that the bigger/first problem is that the red border just appear when it wasnt there and i dont need it nor wanted it, but also that then the border doesnt follow the window. 

Thanks for your pacient and attention

**Comment by gileli121** [comment]
@JaasielCR 
This was a better bug description!
I reproduced it now.
So the key point here is to disable the red border option here: 
![image](https://user-images.githubusercontent.com/17680514/131215384-f2197840-9179-4e95-ac8d-d718758d536a.png)

I am checking now if your report is similar or the same as
https://github.com/BiGilSoft/WindowTop/issues/122

That reported by another user

**Comment by gileli121** [comment]
@JaasielCR 
We will continue to talk about the second issue here:
https://github.com/BiGilSoft/WindowTop/issues/122

**Comment by gileli121** [comment]
@JaasielCR 
Please try the new build that I posted in 
https://github.com/BiGilSoft/WindowTop/issues/122#issuecomment-907613800

And update me there if it fixed for you.
Thanks
