### ISSUE TITLE
Provide mechanism for offline activation

### ISSUE THREAD

**Issue by demdante** [BiGilSoft/WindowTop#130]
Hello.  I purchased the pro version of the software and have it working on my personal computer.  However, I also want to use the pro version on my work computer, but, when I try to activate the pro version on my work computer, the software is telling me that the product key is invalid.  I believe this has less to do with me product key being invalid and more to do with the windowtop software being unable to contact some online resource to verify the product key.  I know this because I can copy the settings config for window top from my personal computer to my work computer, and the pro version works just fine on the work laptop after I reactivate the key.  There needs to be some kind of offline activation method so that people who use restricted or don't even have internet can still use the product.

**Comment by gileli121** [comment]
Released in v5.4.15
Closed.
