### ISSUE TITLE
Opacity Hotkey Not working When Default Set to 3%

### ISSUE THREAD

**Issue by mariop64** [BiGilSoft/WindowTop#135]
As title says, default opacity does't seem to be working at 3% with hotkey toggle. Hotkey sets to 75%

**Comment by gileli121** [comment]
@mariop64 
Please make sure that after you changed the default opacity level, you reopen the window.
The default value is loaded only for new windows detected after the change of the default value.

I can't reproduce the case that the default value of 3% did not work for new windows after the change

**Comment by gileli121** [comment]
@mariop64 
Looks like a bug.
But I can't reproduce it.

What browser did you use?

**Comment by mariop64** [comment]
The opacity issue is the same for these programs I have noticed:
Brave Browser it is a Chrome based derivative for the privacy,
Firefox Browser
Foobar2000 (Open Source Audio Player)

Also I tried added Brave Browser to the whitelist to see if that does anything and it looks like there is a run-away-with-memory effect
![image](https://user-images.githubusercontent.com/31108587/131999019-8d998d2b-7452-48ec-b5a6-d59928402317.png)

**Comment by mariop64** [comment]
EDIT: The issue does occur on Vivaldi as well, seems to be inconsistent.

**Comment by gileli121** [comment]
@mariop64 
I was able to reproduce it.
The clue you gave me is to use the whitelist option.
I did not reproduced yet the issue that it took a lot of RAM

**Comment by gileli121** [comment]
@mariop64 
Please test this build:
[WindowTop Build 04-09-21_1.zip](https://github.com/BiGilSoft/WindowTop/files/7109342/WindowTop.Build.04-09-21_1.zip)

Please make sure to delete the specific configuration for the window.
![image](https://user-images.githubusercontent.com/17680514/132085731-f007ca25-c430-46d3-881c-dc9524eaf745.png)
If you have it, you should see option "Delete window configuration".
Click on this option.

The bug was that it also saved it for some reason

**Comment by mariop64** [comment]
@gileli121 I will be happy to test around Tuesday, away for Labor Day Weekend in USA

**Comment by mariop64** [comment]
The current fix looks fine.

I am trying to see if I can reproduce the issue again, so far, I have not been able to do so consistently, I'll let you know if I can.

**Comment by mariop64** [comment]
When is the fix going to be pushed to the windows store? When I try to update to the latest version it says I already have it. But it doesn't have the fix.

**Comment by gileli121** [comment]
> The opacity issue is the same for these programs I have noticed: Brave Browser (Privacy-Based Chrome Derivative) Firefox Browser Foobar2000 (Open Source Audio Player)
> 
> Notably the opacity issue does not occur in Vivaldi Browser (Chrome based Derivative)
> 
> Also I tried adding Brave Browser to the whitelist to see if that does anything and it looks like there is a crash and run-away-with-memory effect. (32GB Ram Kit) ![image](https://user-images.githubusercontent.com/31108587/131999019-8d998d2b-7452-48ec-b5a6-d59928402317.png)
> 
> Brave Browser shows up as added to whitelist after rebooting the program.

The scenario about high RAM usage was found now
https://github.com/BiGilSoft/WindowTop/issues/155
