### ISSUE TITLE
Crash on startup due to corrupt cache.json

### ISSUE THREAD

**Issue by AdamWHY2K** [BiGilSoft/WindowTop#138]
![7PVQZLGvPA](https://user-images.githubusercontent.com/68286215/132846499-fbcf29c9-a3e2-40fa-bb32-8cbc85eb01e4.gif)

As you can see above the program crashes on startup.

As far as I can tell this is due to cache.json being corrupted
I'll leave a copy of it here
[corrupt_cache.zip](https://github.com/BiGilSoft/WindowTop/files/7143454/corrupt_cache.zip)

Fixed by deleting the corrupt cache and letting WindowTop create a new one on next startup.. not sure what is causing the cache to become corrupt though.

**Comment by gileli121** [comment]
@AdamWHY2K 
Thanks for the report.
Maybe your hard drive is broken... 
I can't explain why it will create a corrupted JSON file.
Maybe it is a very extreme edge case.

Anyway, it should be easy to fix. I just need to catch the exception of it and handle it

**Comment by gileli121** [comment]
@AdamWHY2K 
Here is a  build with a fix for the issue:
[WindowTop Build 14-09-21_1.zip](https://github.com/BiGilSoft/WindowTop/files/7164059/WindowTop.Build.14-09-21_1.zip)

The fix should work also in case it happned for the `settings.json` file

**Comment by gileli121** [comment]
Closed.
If it will reported again, I will reopen
