### ISSUE TITLE
WindowTop.5.5.1.-.Portable.zip is corrupt

### ISSUE THREAD

**Issue by camAtGitHub** [BiGilSoft/WindowTop#145]
Hello again :-)

Trying to download the below file, from releases, results in corrupt file.
I have checked from two PCs.

Thanks

Name: WindowTop.5.5.1.-.Portable.zip
Size: 2860919 bytes (2793 KiB)
CRC32: 11E55F4C
CRC64: 846DE9B121CFFCDF
SHA256: 06B52B0AD3334495A99581916122ACC1D48438183F8AB7FBBFFB9422B44B2A0A
SHA1: 3E6941A9728A6C64E3C23456B3A7693805967C20
BLAKE2sp: 90CEFD81D7B77F832D20B267E8423319263CF7CF2E24E0CC090FD9CAADF8210C
MD5: D4A89D54A5FF76B8CE7EE4CBFF9244F5

**Comment by gileli121** [comment]
@camAtGitHub 
Hi, please try to download v5.5.2 
The last version before v5.5.2 was not good... There were regressions in dark-mode

**Comment by gileli121** [comment]
There is now v5.5.3
Closed for now.
If you still have the issue, please reopen
