### ISSUE TITLE
Live Preview is not working with shrink mode in desktop application - hourglass

### ISSUE THREAD

**Issue by theGateway1** [BiGilSoft/WindowTop#148]
Live Preview is not working with shrink mode in desktop application - hourglass
Steps to reproduce:
1. Download hourglass (Link below)
2. Start a timer.
3. Set it on the top with WindowTop.
4. Shrink the window.
5. Live Preview will stop, unshrink it and you will be able to see the timer going on again.

Hourglass can be downloaded from here: https://chris.dziemborowicz.com/apps/hourglass/

I'm currently in the trial period, and windowtop was working perfectly fine with other applications until now.

![2021-09-22 16_58_43-](https://user-images.githubusercontent.com/70198503/134335767-eb99eb09-f9f7-4b87-974b-57cfaf9a6126.png)

**Comment by gileli121** [comment]
Thanks for the report.
Maybe this app also using chromium.
So maybe this fix: 
https://github.com/BiGilSoft/WindowTop/issues/146
That I am working on will work also for this program.

**Comment by gileli121** [comment]
The fix for #146 will not fix the issue with this app.
Need to figure out another way to fix it.

**Comment by gileli121** [comment]
Closed due to inactivity and low priority (won't fix)
