### ISSUE TITLE
Loss of mouse control during initial setup/entry of key

### ISSUE THREAD

**Issue by RLLaBr** [BiGilSoft/WindowTop#149]
During the initial setup the mouse would only respond in a very odd way, as if another was controlling it. I could move it in the general direction of where I wanted to click, but there was absolutely no accuracy. If I released the mouse, it would wander all over, then suddenly zip to the left side of the screen. This continued until after I entered the key, but only happened when the settings window was on top. After entering the key and closing the settings window, this has not recurred. I have not yet been able to reproduce this.
EDIT: OK, I've been able to reproduce this issue. It seems to happen when making/changing/saving a setting on a Windows Explorer window. It somewhat acts like massive, massive lag, but I had Task Manager open (no problems adjusting settings on that, even with Windows Explorer window open) but saw no increase in mem usage, ethernet usage, cpu usage (AMD Threadripper 2970wx) or gpu usage (AMD Radeon Vega 64). I'll add more info if I encounter it.

**Comment by gileli121** [comment]
@RLLaBr 
This may be the same as
https://github.com/BiGilSoft/WindowTop/issues/131

Do you use Windows 11?

**Comment by gileli121** [comment]
@RLLaBr 
It is fine

Can you confirm what @ACastanza said in #131 that with the last `dev` build (from dev channel) the issue fixed?
If you don't want to install the dev build then it is fine.

Thank you

**Comment by RLLaBr** [comment]
OK, I checked that other post, #131, and watched the video. That is indeed what it looks like, although I didn't get an extra cursor. However the issue does not happen when moving windows around, rather only when I open the Window Top menu bar on the explorer window, and once the menu bar closes, which takes a variable amount of time ranging from about 3 to around 20 seconds, all works well.
 I had not wanted to install the dev versions, but for the sake of troubleshooting this issue, I will.

**Comment by RLLaBr** [comment]
Unfortunately, the latest Dev build repeatedly crashed my system, and Windows update reverted my system back to 22000.194. I checked, and the issue is still there, and is acting exactly as I described before. Sorry, but I won't be able to test the latest Dev build, but the actual roll-out date is only a week or so from now, and I'll recheck it then.
While it did take some doing, I was able to get the Windows explorer window setting saved, and it does display as I set it. The only time I have trouble is if I open the toolbar on the Explorer window. Once the release version rolls out and I receive it, I'll recheck and see if the issue remains.

**Comment by gileli121** [comment]
@RLLaBr 
Thanks for your effort anyway!

We will have to wait to be sure

**Comment by RLLaBr** [comment]
I have an update for you, with a possible clue, maybe.
I had been having more issues than just the one with this software, so last night I took a few deep breaths and did a clean install of Windows 11 252000.194 from the ISO. This is likely the general release, although I think there might be an update on 10/5. Anyway, got it installed, set up, AV and firewall installed, Steam set up, and then I installed Window Top, and activated it. It worked flawlessly. No random movements of the cursor, no doubling of it, no trouble with the Windows Explorer window; it just worked like it should. I really couldn't list all the stuff that was installed vs. what is installed, but if you have a test rig, maybe try installing Transparent Task Bar. Little tsr-style app that does what you think. That was the only app I had installed that altered the default graphics of Windows in any way, and it's not installed now. I did install Lively Wallpaper, which allows animated wallpaper and also can affect the taskbar, but that seems to have no effect on your product.
Either way, Window Top is working as described. Do you think you'll be adding AMD Radeon hardware support? Oh, that reminds me, alt+z is a Radeon shortcut key combo, just to let you know.

**Comment by ACastanza** [comment]
I had neither of those utilities installed at the time I experienced the similar issue.

**Comment by gileli121** [comment]
@RLLaBr  @ACastanza 
I can reproduce the issue also on my side.
There is something I found... Whatever it is a bug in Windows or not, I see how I can trigger this bug (that can be a Windows bug)

So in the next version, I will add some changes that will avoid this issue.

**Comment by gileli121** [comment]
@ACastanza  @RLLaBr 
After more troubleshooting, I confirmed that it is a bug in `SetWindowCompositionAttribute` function (part of the OS) as it said here in Reddit
https://www.reddit.com/r/Windows11/comments/pe3y43/whats_up_with_window_dragging_performance_while/

![image](https://user-images.githubusercontent.com/17680514/135711891-0e45bee1-4e9e-42d0-ab88-f21433f7df7d.png)

I will have to avoid using this function with some parameters that triggers the OS bug

**Comment by gileli121** [comment]
@RLLaBr  @ACastanza 
Please try the build I posted here:
https://github.com/BiGilSoft/WindowTop/issues/104#issuecomment-932840461

Let me know if you get the issue again.
Thanks.

**Comment by RLLaBr** [comment]
Everything seems to be working good now. No trouble with the Explorer window anymore.
