### ISSUE TITLE
Retaining video aspect ratio in PiP mode on multi monitors with varying aspect ratios

### ISSUE THREAD

**Issue by arotora** [BiGilSoft/WindowTop#156]
Hello, I am trying to achieve a certain functionality with this software which I am not aware if is possible yet.   Picture in Picture mode works perfectly fine for fullscreen videos, but I noticed that the videos are always shrunk in my main monitors aspect ratio.

I have tried various work arounds such as placing the video(for example youtube), on a 16:9 monitor, but the PiP seems to always resort to the main monitors native aspect ratio which is in my case 32:9.  This results in the videos to display black bars on either side instead of the native videos aspect ratio.

This can be very well be an issue with the software not targeting specific monitors,  as I have also noticed that having my  windows native zoom percentage differing on each monitor results in  a brief glitch of an oversized video once I exit the picture in picture mode.

Perhaps the other commits that I read about cropping and DPI scaling can potentially alleviate this issue(provide a temporary workaround), but as of now I believe it is just my weird setup that is causing this issue. For clarification purposes, I am using a 32:9(5120x1440p) as my main monitor with two secondary monitors at 16:9(2560x1440p,3840x2160p at 150% DPI scale).  The goal is to create and retain a 16:9 video in PiP without the black bars caused by fullscreening in the 32:9 monitor which seems to occur even if the video was fullscreen in the 16:9 monitor.

Thank you for your time, I apologize if this is confusing to understand.  I would love to clarify further if needed and am willing to troubleshoot further with my weird setup. Great powerful software here.  Looking fowards to how this will grow.

**Comment by gileli121** [comment]
@arotora 
After I checked the code again, I saw exactly how this bug can be reproduced.

The exact scenario is:

**Setup**

_**Monitor A**_
* Set as main monitor
* Have different ratio. For example, resulotion 1366x768

_**Monitor B**_
* Have different ratio. For example - resulotion  800x600

**Steps** 
1. Move the window to monitor B
2. Make it not maximized
3. Shrink it

**Issue**
The ratio of the window will be wrong and calculated according to monitor A because it is the main monitor


I fixed it now. Please try this version:
[WindowTop - Build 31.10.21-1.zip](https://github.com/BiGilSoft/WindowTop/files/7447692/WindowTop.-.Build.31.10.21-1.zip)

**Comment by arotora** [comment]
Hello, it seems that this build is working as intended for shrinking when the video is initially placed in PiP mode, but as soon as I interact with a desktop element it seems to resort back to the previous bug.  Sometimes, it works as intended, but as of now I am able to reproduce this bug quite regularly.  I will send another video.  Thank you for such the quick turnaround time.  The care for this product is astounding!

Note while i was taking the video I discovered that this only occurs when I use the shortcut key.  I will leave the initial information intact up there, but it seems that this bug only occurs when I use the hotkey.  When manually shrinking the video this does not occur.  I will record both in action.

https://dl.dropboxusercontent.com/s/cjbijkv3bep98f6/45ilLbUer2.mp4

**Comment by gileli121** [comment]
@arotora 
I don't have the hardware now (2 monitors) but after checking the code again, I can see a reason why it can happen.
In the video you showed, it got broken about 1 second after you shrink the window, and when you do it via hotkey, it triggered from a different thread and not from the UI thread. so it can explain it...
There is a second thread & code that checks each second if the window got lost by the shrink feature, and I think that the code was executed at the wrong time because of the threads issue...

Please try this build:
[WindowTop - Build 31.10.21-2.zip](https://github.com/BiGilSoft/WindowTop/files/7448190/WindowTop.-.Build.31.10.21-2.zip)

I did here 2 fixes in the code and I hope that if fixed also when you enable it via hotkey

**Comment by arotora** [comment]
I am happy to report that everything seems to work as intended with this latest build!  I'll continue to try to put it through the ringer with weird configurations, but it seems that the main problem has been solved completely.

Thank you so much for this!  I guess the only thing I can suggest is for the ability to freely crop the PiP mode for those that only have a single ultrawide monitor so that they can have for example a 16:9 aspect ratio video in PIP without the side black bars.  That is a completely different story though.  Thanks again.

**Comment by gileli121** [comment]
@arotora 
Great to hear!

>  I guess the only thing I can suggest is for the ability to freely crop the PiP mode

About this, this feature was requested multiple times by users and the ticket about it is #133 

>  for those that only have a single ultrawide monitor so that they can have for example a 16:9 aspect ratio video in PIP without the side black bars

For this, there is a workaround.
You can download Microsoft PowerToys from https://github.com/microsoft/PowerToys/releases 
In this program, you should have the FancyZones.
With the FancyZones feature, you can configure a layout with a 16:9 ratio.
Then you just maximize the window to the 16:9 zone. After that, you shrink it.
It should do the trick if a youtube player honors this zone in fullscreen. If not, the workaround will not work if you set fullscreen

**Comment by gileli121** [comment]
@arotora 
I detected small regression from this fix:
![bug1](https://user-images.githubusercontent.com/17680514/139599651-c7f9f911-c7ee-4ffa-8d27-3d39c26d9dcb.gif)

When the mouse moved outside of the preview (when INTERACT mode is enabled), its size gets corrupted...

Try this build please:
[WindowTop - Build 31.10.21-3.zip](https://github.com/BiGilSoft/WindowTop/files/7449705/WindowTop.-.Build.31.10.21-3.zip)

**Comment by arotora** [comment]
Hello again,  I actually use fancyzones quite often!  It has defintely helped with workflow and can see how it's a potential work around for this feature.  I guess videos in particular are the reason why the cropping feature is so sought after because "fullscreening" a video allows for the hiding of GUI elements, but in turn on ultrawide monitors the black bar is inevitable. This is because as you mentioned, the limitation of fancyzones not actually creating a virtual separated zone, but instead just designating a window in the maximixed state in a particular area of the screen.  For now, the workaround you proposed is definitely useable albeit with GUI elements exposed.

I have actually not tried the interact mode at all!  This actually brings even more funtionality to the software that I was not aware of before.  I guess judging by how you managed to fix this, a lot of the features of the software tie back to the original "standard" state which you have been manually fixing which is much appreciated.

I can confirm that the interact mode works as intended with your fix in the new build.  Thank you for your continued hard work on this issue.

**Comment by gileli121** [comment]
Great!
You may suggest to PowerToys devs to fix it so the zone will work also for fullscreen mode
