### ISSUE TITLE
Change how the FREE version is limited - Instead of blocking some pro features, allow them with limitations

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#158]
People that do not start 30 days trial are not aware of what they are losing. (In the version from MS Store it is harder to start 30 days trial because there is an extra step to login to store so fewer ppl enabling 30 days trial)

So it should be better to allow some of the pro functionality almost the same way it is allowed when the program is activated.

How the features will be limited in the free version:
1. PiP/Shrink + Interact + Auto-Move: Will be allowed in the free version with a limitation of time. after 20 minutes, live preview & interact & Auto-Move will be disabled (if any of them are enabled). Program restart is needed to allow it again.
2. Anchors - Will be limited to 1 hour and will be disabled each time after 1 hour.  Program restart is needed to allow it again.
3. Red border highlighter for top-most windows - The highlighter will be shown for 20 minutes (in case the user enabled the option under the SET-TOP feature)

Any other features or functionality will be disabled as it is now.

When 30 days trial started, it will work without any limitations (as the full version)

**Comment by Gitoffthelawn** [comment]
Hi Gil.  Because this may be a little confusing to some people, if you need help refining the English description of this change, just let me know.

**Comment by gileli121** [comment]
I am not sure yet that it will be done

**Comment by gileli121** [comment]
I am closing this task for now.
If I will decide that it should be done, I will reopen it

**Comment by gileli121** [comment]
This ticket is in progress & testing phase

**Comment by gileli121** [comment]
Implemented in 5.32.2

**Comment by gileli121** [comment]
A critical bug has been identified in this version. The software may enter a broken state where a fatal exception window appears on every launch.

This will need to be addressed.
