### ISSUE TITLE
Add Portuguese language

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#165]
Thanks to `Geovane Souza`, we have now translation for Portuguese.
Here is the first version for a test with this translation:
[WindowTop - Build 10.11.21-1.zip](https://github.com/BiGilSoft/WindowTop/files/7515548/WindowTop.-.Build.10.11.21-1.zip)

**Comment by Geovanesou** [comment]
![image](https://user-images.githubusercontent.com/57776388/141284160-2b9643d2-9d18-4ef5-a9a9-af59f3bf0f9d.png)
Please, capitalize the first "p" to make it Portuguese!!

**Comment by Geovanesou** [comment]
![image](https://user-images.githubusercontent.com/57776388/141298009-85661d75-d32f-4af5-a125-7a24b03350ca.png)
These lines are not avaluable for translate...

**Comment by Geovanesou** [comment]
![image](https://user-images.githubusercontent.com/57776388/141298660-b4d67f84-ed00-4e5a-b812-4b69e6b2942d.png)
Not translated too...

**Comment by gileli121** [comment]
@Geovanesou 

> ![image](https://user-images.githubusercontent.com/57776388/141284160-2b9643d2-9d18-4ef5-a9a9-af59f3bf0f9d.png) Please, capitalize the first "p" to make it Português (Portuguese)!!

Fixed



> ![image](https://user-images.githubusercontent.com/57776388/141298009-85661d75-d32f-4af5-a125-7a24b03350ca.png) These lines are not avaluable for translate...

I don't think that translation is needed here



> ![image](https://user-images.githubusercontent.com/57776388/141298660-b4d67f84-ed00-4e5a-b812-4b69e6b2942d.png) Not translated too...

How did you reproduce it?
I could not reproduce it again


Here is the updated build:

[WindowTop Build 20.11.21-1.zip](https://github.com/BiGilSoft/WindowTop/files/7574489/WindowTop.Build.20.11.21-1.zip)

In addition, this build contains also the following fixes:

* Potential fix for issue #129 that somehow the app thinks that it is already running
* Fixed bug that sometimes the settings window frozen

Let me know if this version is fine
