### ISSUE TITLE
When I upgraded the BIOS, the activation would fail, indicating that it was a new device

### ISSUE THREAD

**Issue by Luminphantom** [BiGilSoft/WindowTop#167]
So how can I solve this problem, I have a PC and a  Dell laptop,  each time I upgrade my BIOS, the activation would fail. As you know, one key can only activate 3 devices, so it is easy to reach the upper limit of the device.

**Comment by gileli121** [comment]
@Luminphantom 
It is a known issue. A workaround developed here:
https://github.com/BiGilSoft/WindowTop/issues/134

It did not ask you if you want to reset the use count?

**Comment by Luminphantom** [comment]
Thank you very much!
