### ISSUE TITLE
Unable to Uninstall the program

### ISSUE THREAD

**Issue by Dco909** [BiGilSoft/WindowTop#168]
I'm currently using WindowTop.5.6.. I am trying to uninstall the program from my computer, but I keep getting an error message saying that WindowTop is running and to close out first. I am closed out of all windows on my computer when I'm trying to uninstall. Any ideas on how I can uninstall working around this issue?

**Comment by gileli121** [comment]
@Dco909 

I could not reproduce this bug on my side.
I tried to reproduce it with v5.6.7 and v5.6.9 and in both cases it worked as expected (I first had to exit the program).
Did you exit the program before right?

Anyway, if nothing helps, please do the following steps:
1. Open task manager - See [https://geekflare.com/how-to-open-the-task-manager-in-windows/](https://geekflare.com/how-to-open-the-task-manager-in-windows/) 
2. Go to the "Details" tab:
![image](https://user-images.githubusercontent.com/17680514/143808773-9d51ee9a-2e3d-4013-9caf-7461a05a72da.png)
3. Find all "WindowTop.exe" processes (You should find maximum 2 processes) and for each process, right click and choose "End process tree"
![image](https://user-images.githubusercontent.com/17680514/143809228-284ab139-4292-413e-ba7a-9dd0945f7eda.png)
4. Repeat step 3 if you still find more "WindowTop.exe" process
5. Try to uninstall again


Let me know if it helped.

Btw, may I know what you try to uninstall?

**Comment by gileli121** [comment]
Closed for inactivity
