### ISSUE TITLE
Unlock the red-frame feature of top-most mode

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#169]
Because of https://github.com/microsoft/PowerToys/issues/13  and https://github.com/microsoft/PowerToys/pull/14360#issuecomment-983834362 
We will need to unlock the feature to show the frame around the top-most window.
The feature will be free in the next version.

They are very good at coping with good ideas

**Comment by WZ-Tong** [comment]
Maybe we can change the frame's color to fit our theme?
Just a small but useful improvement

**Comment by gileli121** [comment]
@WZ-Tong 
Good idea and easy to implement.
Please open new request under the issues page
