### ISSUE TITLE
Windows Apps losing TopMost functionality after going fullscreen

### ISSUE THREAD

**Issue by scorpion421** [BiGilSoft/WindowTop#171]
Example: Netflix app for Windows
Windowed and maximized is no problem, but after going fullscreen, the TopMost hook seems to be reverted. The icon still is set like it would be TopMost, but isn't anymore. You can disable and re-enable it to get it to work again, but only until you go fullscreen again. Something seems to have to do with the "Application Frame Host" (ApplicationFrameHost.exe) I think.

Maybe an option like "check for title" and "check for LeaveFullScreenMode" could help in this case? Like for apps, running via "Application Frame Host"? Just a quick thought. Because if we could detect "LeaveFullScreenMode", the hook could get reapplied as soon as the state of the window changes back to windowed/maximized. Sure, only if this is the issue that the hook for TopMost is lost :). 

I am using the latest version (5.7.0) at Windows 10 Pro.

Thanks for any fixes or clues!

**Comment by gileli121** [comment]
Thanks for the report.
Do you have example for app that have full screen that I will use to reproduce the issue?

**Comment by scorpion421** [comment]
Sure. Like I previously named: The Netflix App itself :)
https://www.microsoft.com/p/netflix/9wzdncrfj3tj

**Comment by gileli121** [comment]
@scorpion421 
Reproduced

**Comment by gileli121** [comment]
@scorpion421 
Please check this version:
[WindowTop 5.7.7-beta - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/7790572/WindowTop.5.7.7-beta.-.setup.exe.zip)

Should be fixed now.

**Comment by scorpion421** [comment]
Confirmed. Working like intended :). Thanks for the investigation and fix!

**Comment by gileli121** [comment]
Great!
Closed
