### ISSUE TITLE
[Feature Request] Customize frame color for top mode

### ISSUE THREAD

**Issue by WZ-Tong** [BiGilSoft/WindowTop#172]
Get an option to change color, get a chance to fit my theme.
Easy to implement, very useful

**Comment by gileli121** [comment]
Working on it now

**Comment by gileli121** [comment]
@WZ-Tong 
Please try this version:
[WindowTop v5.7.3 - 25.12.21.zip](https://github.com/BiGilSoft/WindowTop/files/7775303/WindowTop.v5.7.3.-.25.12.21.zip)

Let me know how it works.
Thanks

**Comment by WZ-Tong** [comment]
It's alright, wait for released version!

**Comment by gileli121** [comment]
@WZ-Tong 
Released now in v5.7.4
Soon will be available in the store also
