### ISSUE TITLE
[Anchors] Implement drag/drop to window via the anchor

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#180]

**Comment by gileli121** [comment]
First preview:
![drag_to_anchor_demo](https://user-images.githubusercontent.com/17680514/147711436-886d1e73-1864-40d9-b374-c98263875bca.gif)

**Comment by gileli121** [comment]
Beta build:
[WindowTop 5.7.7-beta-2 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/7791048/WindowTop.5.7.7-beta-2.-.setup.exe.zip)

**Comment by jakkaas** [comment]
Wow. You are super quick. Awesome

**Comment by gileli121** [comment]
Thanks :)
It took 2 hours but it could take less..
Btw, the thing that I don't like in developing WindowTop is that I want to use it while I am working.
But I can't because I developing it

**Comment by gileli121** [comment]
Released in v5.7.7
Will be also available soon in the store

**Comment by jakkaas** [comment]
Any other reason why is it not working for me? When I am dragging it to anchors it is showing cross mark and I can't drop it. Any setting required which I have disabled?

**Comment by gileli121** [comment]
@jakkaas 
I found that if the app configured to run as admin, it will not work.
Did you configured it to run as admin?

**Comment by gileli121** [comment]
@jakkaas 
I saw it also.. it is because the installer run the app as admin.
After you finish to install it, the installer run the app as admin user.
If you exit the app and run it again it should work fine if the option to run as admin is disabled

**Comment by jakkaas** [comment]
Yes i am running it as admin. I will disable it. Wont it affect other functions by not running as admin?

**Comment by gileli121** [comment]
The only downside when not running as admin is that it will not control any program that running as admin.
In most cases your programs will not run as admin anyway so you should not notice it

**Comment by jakkaas** [comment]
Yup its working in non admin mode

**Comment by jakkaas** [comment]
But as i am using onenote and edge. After shrinking windows in non admin mode and then trying to unshrink it again non admin mode using hotkey is not happening. So currently I will use in Admin mode

**Comment by gileli121** [comment]
@jakkaas 
I reopened this task and will try to make better implementation that works also when the app running as admin

**Comment by gileli121** [comment]
@jakkaas 
I fixed this issue when the app running in Admin mode.

Please test this version and let me know how it works
[WindowTop 5.12.5-beta1 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/8926855/WindowTop.5.12.5-beta1.-.setup.exe.zip)
s for you in Admin mode:

**Comment by gileli121** [comment]
Found a mistake in the fix.
Dragging from admin app to anchor while WindowTop is running as Admin will not work

New fix:

[WindowTop 5.12.5-beta3 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/8931307/WindowTop.5.12.5-beta3.-.setup.exe.zip)

**Comment by gileli121** [comment]
Seems to work fine
Released in
https://github.com/BiGilSoft/WindowTop/releases/tag/v5.12.5

If there are any issues, feel free to reopen.
