### ISSUE TITLE
Text color makes text very hard to read

### ISSUE THREAD

**Issue by demdante** [BiGilSoft/WindowTop#182]
I realize that, in the grand scheme of things, this is a very nitpicky issue, but figured I would still at least create a issue for it.  Right click the windowtop system tray icon, expand "settings", and select "All Settings."  In the all settings window, navigate to the "About" section and click the "Check for updates" button.  I get the feeling that the windowtop settings window was designed with windows 10 specifically in mind, because, when you look at the window in windows 11, I don't know about you, but I can't see what this says at all:

![image](https://user-images.githubusercontent.com/64720591/148039834-4a1b999c-91e8-465d-9450-aa54918fc89e.png)

Now, I can infer, based on the color, that the latest version is installed and no updates are available.  However, if the color was all that mattered, why not just display a green or red box of color?  Basically, what I am saying here is maybe use a darker green when displaying this text

**Comment by cpasoft** [comment]
I agree with it...
Also it would be great that appear the beta version you are using (if is the case).
I can see version 5.7.7 instead of 5.7.7-Beta2
![imagen](https://user-images.githubusercontent.com/29692062/148041649-1daad477-8984-4de0-a6c7-0f043bb3a87f.png)

**Comment by gileli121** [comment]
@cpasoft 
Thanks for the report.
I will fix this issue:
![image](https://user-images.githubusercontent.com/17680514/148049019-4283455b-0d04-4495-97a0-5096d282f823.png)

About:
![image](https://user-images.githubusercontent.com/17680514/148049045-3cc0a50b-576b-4258-b38e-41fc35546a6e.png)

I know about it. But it is minor issue that it can't show if it is beta version.
I prefer to use the time to implement more important functionality

**Comment by cpasoft** [comment]
Not worries about the beta version print in the about section... ;-)

**Comment by gileli121** [comment]
![image](https://user-images.githubusercontent.com/17680514/148646028-642b9b43-220e-4a82-b5d3-790bb8d0071f.png)
Fixed
