### ISSUE TITLE
WindowTop v5.7.8 Setup.exe is zipped

### ISSUE THREAD

**Issue by OfficialEsco** [BiGilSoft/WindowTop#186]
Hey, Winget Package Contributor here, why is the WindowTop v5.7.8 Setup.exe zipped?
![firefox_E6asOJzyzV](https://user-images.githubusercontent.com/15158490/148649369-b3bc5c86-d940-453d-95e9-92adaf8a3659.png)

**Comment by gileli121** [comment]
Hi, I found out that when it is zipped and you unzip it yourself, it will remove this window
![image](https://user-images.githubusercontent.com/17680514/148649880-db1f82f4-7d42-49ee-9cab-7488aacd1624.png)

**Comment by OfficialEsco** [comment]
Aha, weeeeell, that window will go away once Windows Defender SmartScreen have scanned the software for potential harmful code, and since we submit it to winget it should be approved by every AV vendor pretty quickly

But if that is what you want to do you'll do that :)

**Comment by gileli121** [comment]
This is what I found. I tested it on another computer and saw this behavior.. 
Thanks for providing this installation solution.
I need to add your installation method in the download page :)

**Comment by OfficialEsco** [comment]
> I need to add your installation method in the download page :)

If you decide to do the zipped method we won't be able to submit new versions because we're waiting for https://github.com/microsoft/winget-cli/issues/859

**Comment by gileli121** [comment]
OK, So I will do both. But you will not see it in the release description.
You will need to look for the link here:
![image](https://user-images.githubusercontent.com/17680514/148650508-e98bd4ee-f94e-4072-945c-79f1fe91ca3b.png)

**Comment by OfficialEsco** [comment]
Great, thanks 😁
If you don't mind me asking, why are you adding minor versions into the Major version release instead of making a new release for each version? (This can break some automation regarding RSS feeds)

**Comment by gileli121** [comment]
Good question.
I considered it very hard to call it v5.8 (instead of v5.7.8)
I did not did it because of marketing reasons. this way if you go to the download page you will not miss any of the hard work and good stuff that was done.

But I think that in this case it was too much and I was supposed to call it v5.8

**Comment by gileli121** [comment]
@OfficialEsco 
Do you think that I should do it in a different way?

**Comment by OfficialEsco** [comment]
The normal way of doing GitHub releases is to make a new release/tag for each version, aka `5.7(.0)`, `5.7.1` ,`5.7.2` etc (just noticed you did this back in version 3.3.X), that way its easier to maintain RSS feeds because we see this https://github.com/BiGilSoft/WindowTop/tags (a new tag triggers a action like updating the software)

And in some cases its easier to see the patch notes on the releases page, however you've actually managed to make a pretty cool patch note so i'm kinda conflicted about what to say 😁

I'm not here to make you change your mind about anything, its just about convenience for Package Managers, which i guess makes it a bit harder for you since you've decided to do it this way

Feel free to close

**Comment by gileli121** [comment]
OK, thanks for sharing your thoughts. 
Next time I will try to reduce what I did. I will keep my style but I will not mix too much new stuff in minor versions.
I will try to see how to keep cool release notes without putting new features in minor versions.

Btw, the number 5 is not going to change and there is no plan to do it. This number changed from 4.X.X to 5.X.X when the app was rewritten to C#. I think that this was the only valid case. I think that the version should start with 2.X.X and not 5.X.X.
But it is too late now.

It changed from 3.X.X to 4.X.X when only part of it was ported to C# (the UI part). Then it changed from 4.X.X to 5.X.X when it was fully ported C# from AutoIt.

Btw, where is the download/installation instructions page for the the

**Comment by OfficialEsco** [comment]
in theory here: https://docs.microsoft.com/en-us/windows/package-manager/winget/
WinGet should be distributed to every Windows PC above 1709, so you should in theory say `winget install gileli121.windowtop -e` 

Did some testing since you also release to Microsoft Store
`winget show windowtop -e`  and `winget show WindowTop -e` seems to prioritize the exe version, so to install the Microsoft Store version it would be `winget install 9PG6GHB4CT57` which seems way too scary to have on the instructions page 😁

**Comment by gileli121** [comment]
@OfficialEsco 
I think that I really did a mess here.. Now when I want to release hotfix I can't do it in a way that it will looks normal.
I think that may best option is to release v5.8.0 (in addition to v5.7.8) with major release notes from v5.7.8 and few hotfixes.
I have no other choice that I can see

**Comment by gileli121** [comment]
And maybe I will make v5.7.8 unavailable to make it looks more sense

**Comment by OfficialEsco** [comment]
Hmm, what makes 5.7.8 so special? From my POV it looks like 5.6.X where you have both Optimize, Improved, Implement and Fixes, why can't you do 5.7.9 for the hotfix?

**Comment by gileli121** [comment]
@OfficialEsco 
There are major improvements in v5.7.8 for the Anchors feature.

These fixes are major:
Implemented: Anchors - Option to hide text for anchors if icons are selected (#181)
Implemented: Anchors - Added option "Always show window title for duplicate icons" (#181)
Implemented: Anchors - Added option to make the anchors bigger when they most recently used (#181)
Improved & Implemented - Anchors - Added preview for the style configuration (#181)

I used to have a general role: If you have a lot of stuff that starts with "Implemented:" - then I should change the number in the middle and not the last number after the dot.
I used to follow this role until 5.6 but in 5.7.X I broke the role because I wanted cool release notes but now I see that it making mess. But maybe it is just me.

**Comment by gileli121** [comment]
I think that I will do as in https://github.com/JanDeDobbeleer/oh-my-posh/releases
Looks like every time there is "Features" you increase the middle number.

It is similar to my role but in my role I said that to increase the middle number you need nice amount of features

**Comment by OfficialEsco** [comment]
IMO any Implementations should get a new version number
`MajorChange.NewFeature.Hotfix` would make your life a lot easier and the patch notes would still be good, IMO people don't look at the pictures/gifs, they look at the Text then the Pictures/Gifs for reference
And when you implement something new in X.X.* people will think its a hotfix

**Comment by gileli121** [comment]
I will do it this way. I also see how it will make my life easier.
But it also means that the middle number is going to increase a lot

**Comment by OfficialEsco** [comment]
That does not really matter :) It just means you've found A LOT of Improvements

**Comment by gileli121** [comment]
What is `MajorChange` ? 
In my case, I consider `MajorChange` when the app was rewritten.
Are there other cases?

**Comment by OfficialEsco** [comment]
In some cases yes
In Oh My Posh's example its this apparently
https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v6.0.0
https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v5.0.0
https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v4.0.0

But i believe its just a split to increase the version number since his 3* version went up to 3.181.2

**Comment by gileli121** [comment]
Looks like when there are BREAKING CHANGES he change the first number right?
It is not going to happen.
Removing feature considered as breaking change

**Comment by OfficialEsco** [comment]
I think so yes, or since you are releasing to Microsoft Store dropping support for a Windows 10 version

**Comment by gileli121** [comment]
I am considering to remove the "Glass Mode" feature because it is unstable and no one use it from what I know.
Removing unused, unstable feature is a reason to change the first number?

**Comment by gileli121** [comment]
I think that no

**Comment by OfficialEsco** [comment]
Na, not since its unstable

**Comment by gileli121** [comment]
OK, Thanks
