### ISSUE TITLE
[Opacity] Add option in opacity to change back to 100% when the mouse is above the window

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#190]
User requested this feature

> Hi is there a way to set window opacity back to 100% when mouse over? it would be very useful. thanks

**Comment by jakkaas** [comment]
All concepts you are planning are really useful and super. Waiting for updates, especially this one.

**Comment by gileli121** [comment]
@jakkaas 
Soon I will give you beta version to test it with

**Comment by gileli121** [comment]
@jakkaas 
Implemented:
![opacity_auto_disable_demo](https://user-images.githubusercontent.com/17680514/149513338-16d941ac-29b9-45dc-9472-a130fcc3fbc9.gif)

See this beta:
[WindowTop 5.8.0-beta1 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/7870205/WindowTop.5.8.0-beta1.-.setup.exe.zip)


Some features take 1-3 weeks to develop... Other features like this one took 4 hours.
Let me know how it works

**Comment by jakkaas** [comment]
Sure. Would test and let you know

**Comment by gileli121** [comment]
@jakkaas 
I found a bug that the feature does not work when the toolbar is disabled.
I will fix it now.

**Comment by gileli121** [comment]
@jakkaas 
Fixed here:
[WindowTop 5.8.0-beta2 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/7870612/WindowTop.5.8.0-beta2.-.setup.exe.zip)

**Comment by gileli121** [comment]
@jakkaas 
Any update? I am wondering if after this one I should work next on https://github.com/BiGilSoft/WindowTop/issues/194 or on https://github.com/BiGilSoft/WindowTop/issues/185

**Comment by jakkaas** [comment]
Tested with few windows. Currently working as expected. Opacity changes back to normal on mouse hover

**Comment by gileli121** [comment]
Thanks, released in v5.8.0
