### ISSUE TITLE
[Anchors] Suggestion: Allow to set a contour or a background to the anchors

### ISSUE THREAD

**Issue by cpasoft** [BiGilSoft/WindowTop#201]
When you have a desktop remote control, you cannot distinguish the real remote control icons with the anchors of your host.
I'd like to have a contour or something to distinguish the anchors vs. real icons on the remote desktop.

![imagen](https://user-images.githubusercontent.com/29692062/154457830-6ac4e07a-8cce-4f9e-8dcc-759d905618ab.png)

**Comment by gileli121** [comment]
@cpasoft 
Sounds like edge use case.
And still, I don't understand why you can't distinguish anchors from desktop icons.
Desktop icons always have text unlike anchors.
In addition, the text of desktop icons is below the icon and left/right to the icon.

So I don't understand why you say it.

**Comment by gileli121** [comment]
No response from user, closing
