### ISSUE TITLE
Opacity flashing when applied to Steam

### ISSUE THREAD

**Issue by AdamWHY2K** [BiGilSoft/WindowTop#205]
Happens when applied to [Steam music](https://i.imgur.com/l7Fadkc.gif) or when interacting with [Steam's main interface](https://i.imgur.com/H8rHpC6.mp4).
Doesn't happen with Steam friend's list or chat windows though.

Windows Version: 10.0.19043 Build 19043
WindowTop Version: v5.10.0

**Comment by gileli121** [comment]
@AdamWHY2K 
Unfortunately, there is no way to fix the issue with steam because steam is modifying it's opacity by itself for some reason.
I don't see valid reason why steam would do it.. Maybe you can ask this question in their support but it is unlikely that they will change it.

Sorry
