### ISSUE TITLE
[Anchors] Minimize window with right click on "Anchors" icon

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#213]
### Discussed in https://github.com/BiGilSoft/WindowTop/discussions/211

<div type='discussions-op-text'>

<sup>Originally posted by **xmaxrayx** March 14, 2022</sup>
https://i.imgur.com/EK66ycj.png</div>

**Comment by cpasoft** [comment]
It would be great that with Caps+Right click will close the window, and right click only minimize.

**Comment by gileli121** [comment]
@cpasoft 
I liked the idea!
More simple for the user (one click instead of 2 clicks) and also more simple to develop 

I will open it for configuration so the user can configure what right-click does.
The options for right-click are:
1. Minimize the window
2. Close the window
3. Open right click menu with the options: "Minimize", "Close", "Settings".
Under "Settings" you have the option to configure if right-click will do 1. or 2.

**Comment by gileli121** [comment]
@cpasoft 
I think that we can make use also of the middle click on the mouse.

If you agree with the idea, the question is what is the default for the middle click?
It can be:
1. Close the window
2. Minimize the window

And what should be the default for right-click?
It can be:
1. Open right-click menu (with "Minimize", "Close", "Settings")
2. Minimize the window
3. Close the window

**Comment by xmaxrayx** [comment]
@gileli121  I will suggest:
-Left click = open
-Right click = minimize
-Middle click = Close app or  do "PIP" future 
-add "Ctrl" "Shift" support like you can (ctrl + right click) to close.

**Comment by cpasoft** [comment]
I like both... I do not use PIP so much, but I think is a good idea use middle click for that...

**Comment by gileli121** [comment]
I will start working on it now.
Thanks for your feedbacks

**Comment by gileli121** [comment]
@cpasoft @xmaxrayx 
Check this version:
[WindowTop 5.12.0-beta1 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/8422357/WindowTop.5.12.0-beta1.-.setup.exe.zip)

I added these options:
![image](https://user-images.githubusercontent.com/17680514/161864953-df0e9fce-de8d-40a6-9b1e-fe3ef2d50850.png)
![image](https://user-images.githubusercontent.com/17680514/161864995-27f191b3-c15b-48a2-bf47-2b383b43f91a.png)
![image](https://user-images.githubusercontent.com/17680514/161865029-c1e2077b-9947-48df-ac6d-1787a0f72134.png)


Let me know how it works.

Thanks

**Comment by cpasoft** [comment]
Testing and working on Windows 10...
I like the "Open right click menu" feature...

**Comment by gileli121** [comment]
@cpasoft 
Thanks!

Please check this version:
[WindowTop 5.12.0-beta2 - setup.zip](https://github.com/BiGilSoft/WindowTop/files/8455889/WindowTop.5.12.0-beta2.-.setup.zip)

I added here just a tips window that will open when you first use it.

**Comment by gileli121** [comment]
@cpasoft / @xmaxrayx 
Any update about v5.12.0-beta2 ? 
Can I release it?

Thanks

**Comment by gileli121** [comment]
OK,
No problem
I will wait for your feedback

**Comment by gileli121** [comment]
@cpasoft 
Somehow I missed the notification about your last message here.
Great to hear about it!
I will make a release tomorrow :)

**Comment by gileli121** [comment]
@cpasoft 
I am waiting for the translation to Chinese for the new stuff that was added to this feature.
You're from china right? If so, maybe you can help translate it also in case I need it?

**Comment by xmaxrayx** [comment]
@gileli121  sorry was busy,
yeah work great on win10 21H2.
thank you for bring this future <3.

**Comment by gileli121** [comment]
@cpasoft @xmaxrayx 
Released in https://github.com/BiGilSoft/WindowTop/releases/tag/v5.12.0 
Enjoy and thanks for you feedback and testing efforts!

**Comment by cpasoft** [comment]
> @cpasoft I am waiting for the translation to Chinese for the new stuff that was added to this feature. You're from china right? If so, maybe you can help translate it also in case I need it?

Nope... sorry. I cannot speak Chinese... :-(
