### ISSUE TITLE
Incompatible ? QTtabBar <> WindowTop ?

### ISSUE THREAD

**Issue by DBX31** [BiGilSoft/WindowTop#215]
Hi,

I use QTTabBar since... many month and it's really great tools.
You program is one really good complement. But, I think the interaction between the 2 program is very bad.
Can you maybe able to activate WindowTop menus with if I push a bouton from keybard ? Or something like that ?

Thanks
Regards
DBX

**Comment by gileli121** [comment]
@DBX31 
Maybe you will no longer need  QTTabBar because Microsoft is going to include tabs in file explorer natively (built-in) in the next versions of Windows 11.
https://www.youtube.com/watch?v=o3mZpnzTzzM

**Comment by DBX31** [comment]
Yes, but I don't use it for this.
I use the quick view function (small button down right of icon).
![explorer_NQgqpwEMeJ](https://user-images.githubusercontent.com/102855534/161378863-36959cd4-deb6-4c02-821a-c8fcd018cf27.png)

If I move the mouse:
![explorer_KnhFZYLk7L](https://user-images.githubusercontent.com/102855534/161378892-897f452f-a46d-4bf3-8f67-6fec8ceda18b.png)
(QQtabbar menu remove by WindowTop menu)
![explorer_n1N2dMTE0S](https://user-images.githubusercontent.com/102855534/161378940-f399a1a4-a4fa-4a87-8334-89875c3c2771.png)

**Comment by DBX31** [comment]
My system is under windows 11.
Maybe it's possible to hiden the green arrow ?

**Comment by gileli121** [comment]
@DBX31 
Thanks for the report.
If you don't need the arrow, you can disable it by clicking here:
![image](https://user-images.githubusercontent.com/17680514/161379438-4254be9b-098d-473c-9c08-6d8ffa9f4760.png)

You can configure hotkeys instead.

**Comment by gileli121** [comment]
@DBX31 
Maybe a better workaround is to do these steps:
![image](https://user-images.githubusercontent.com/17680514/161379512-54c0a03e-933f-4129-a80e-581968a19223.png)
![image](https://user-images.githubusercontent.com/17680514/161379535-e1c57cde-1cba-412b-b390-636084db1d5d.png)
![image](https://user-images.githubusercontent.com/17680514/161379560-035a97b2-8798-4a81-bc1e-0a53bcc402c7.png)

**Comment by DBX31** [comment]
Hi

I have do the first issu but now, QTTabBar don't display the button....
I have already try the blacklist without succes.

Find :
![hgzMk3kBDN](https://user-images.githubusercontent.com/102855534/161379983-ee444bcd-1b78-4006-bb46-37e8249f0412.png)
![explorer_SiFIgbwXAY](https://user-images.githubusercontent.com/102855534/161379995-206b6e41-afbc-4e91-83db-72f5290fa444.png)
 
And, sometime, WindowsTop is blocked without display toolbar menu. Stop, quit, restart don't change...

**Comment by DBX31** [comment]
Restart computer resolve this...
For me, the first solution will be to have the possibility to desactivate the arrow.
It is possible to do that in another update ?
tks

**Comment by DBX31** [comment]
Hi,
What do you think to include the desactivate the arrow ?

**Comment by DBX31** [comment]
Hi,

Another use problem... it's ok but if it's possible to disable for this:
![explorer_JfvdEUJm5S](https://user-images.githubusercontent.com/102855534/161425502-31d8ae74-d136-468b-85d3-893aeee7c52b.gif)

Apps is "Pantherbar". In task windows, I see the program use Runtime Broken...

Regards
DBX

**Comment by DBX31** [comment]
Hi,
Finnaly for "Pantherbar", it's resolved.... "Runtime Broker" is in folder "System32", and the name of file is: "runtimebroker.exe.
The function "blacklist" run like a charm ! Very good !.

For QTTabBar, I have not find a solutiuon. Actually, I use hotkey for active/desactivate when I need... it's ok but not really nice...

Thanks again for your program, it's really a muste have !

Regards,
DBX

**Comment by DBX31** [comment]
Hi,

Ok, I have find a great solution... inclide Explorer in the black list.
Now, it's ok. Just this program don't have the special minimise button but all other of the system yes §

Regards
DBX
