### ISSUE TITLE
The auto hide taskbar function of Windows 11 can not be used normally

### ISSUE THREAD

**Issue by ltxman** [BiGilSoft/WindowTop#221]
When you use windowtop and turn on the automatic hidden taskbar function of windows11, the automatically hidden taskbar cannot be called normally when the mouse is close to the bottom.

**Comment by ltxman** [comment]
It's normal

**Comment by gileli121** [comment]
@ltxman 
Seems that you are not the only one.
Do you know what you did so the issue stopped happening?

**Comment by ltxman** [comment]
> @ltxman 
> Seems that you are not the only one.
> Do you know what you did so the issue stopped happening?
> 
> 

Just quit and reopen it.

**Comment by gileli121** [comment]
I was able to reproduce the customer issue only once and it is not enough for me to track down the actual cause.
But based on his input I guess that somehow maybe I can fix the bug by running the code from the same UI thread that used to power the toolbar.

I hope that my guess is right.
Here is the beta version with the fix included:

[WindowTop 5.12.2-beta2 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/8743642/WindowTop.5.12.2-beta2.-.setup.exe.zip)

This link is not for you @ltxman . 
I am talking with him via email and I use this place for uploading test versions.

**Comment by gileli121** [comment]
I did a mistake.
The last fix that I posed is about an issue that when enabling shrink with a hotkey, the window disappeared, and it working as expected when enabling shrink via the toolbar.

So I reopened this by mistake because this one was not reported twice.
I will close this issue but will keep the last link...
