### ISSUE TITLE
Implement that the app will ask you to rerun it as admin when user try enable Top-Most / Shrink modes for admin window

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#241]
### Discussed in https://github.com/BiGilSoft/WindowTop/discussions/224

<div type='discussions-op-text'>

<sup>Originally posted by **ruike-kj** May  8, 2022</sup>
微软商店购买的wintop，怎样设置以管理员开机启动
![2022-05-08_111647](https://user-images.githubusercontent.com/78640327/167280200-625dab39-2d3d-4b8a-96b2-bacf314e1089.jpg)</div>

**Comment by gileli121** [comment]
First version with the implementation is out:
![image](https://user-images.githubusercontent.com/17680514/177015086-e62aede4-f83c-45f5-92e8-c4d4e845f130.png)

If you see this notification below, when you try to do something like set the window on top, the OS will ask you to give WindowTop "admin" access. 
Note that this will not restart the app! 

If you really want to know what happens, then it just creates a background WindowTop process helper with admin access.
The main WindowTop instance will communicate with the background admin process. 

When a window is identified as "inaccessible", it will use the second background process to send the API requests to OS (things like set it on top, etc)

If you see this:
![image](https://user-images.githubusercontent.com/17680514/177015198-a9a28e0b-5e67-4039-ab72-f051c8063c7e.png)

And enable for example "Set-Top" mode, the OS will ask you to approve the request.
After that, the window will become on top. :) 
Now, if you will check the toolbar again on that window, you will not see anymore this:
![image](https://user-images.githubusercontent.com/17680514/177015221-43bb1b85-240c-4b91-9d51-84ed59abcb66.png)

Because at this point, you already gave WindowTop the permissions.

When you try to enable it via hotkey, the same flow applies.
But in case of a hotkey trigger, you will see this notification before the OS request:

![image](https://user-images.githubusercontent.com/17680514/177015265-0f5c7aab-0386-4015-8a8f-e54dca8ba073.png)


Few notes:
There is still work to do here...
Currently, there is some issue with the settings.
If you change the settings, you will need to restart WindowTop so the changes will take effect. 

I will fix it soon.
Other than that, this feature should be ready.


Here is the test version:

**Comment by ruike-kj** [comment]
什么时候微软商店的版本可以更新啊

**Comment by gileli121** [comment]
@ruike-kj 
I still did not implement it for the store version.
I will work on it today.

I am not sure that I can provide an installer for the store version (for testing it like what I do with the regular version)
But I will try

**Comment by gileli121** [comment]
@ruike-kj 

1. 
Here is the store version for testing:
https://github.com/BiGilSoft/WindowTop/releases/download/v3.0.8-free/UWP_PackagingProject_5.14.0.0_Test.zip

2. Extract the zip file

3. Install the certificate file: `UWP_PackagingProject_5.14.0.0_x64.cer` 
![image](https://user-images.githubusercontent.com/17680514/177218279-e6377742-e729-4d66-8d41-a4202b2d3613.png)

3.1 
![image](https://user-images.githubusercontent.com/17680514/177218408-81fb4318-d227-4219-bb0c-16254b499c2e.png)

3.2 
![image](https://user-images.githubusercontent.com/17680514/177218458-ac19167e-4610-4bb6-9665-f053b07e5316.png)

3.3
![image](https://user-images.githubusercontent.com/17680514/177218531-ca7dc8ba-cd32-4612-9889-bcb0b80c93bf.png)

3.4
![image](https://user-images.githubusercontent.com/17680514/177218564-3cd5863a-9e6d-4bab-b910-b56ea26490c3.png)

3.5
![image](https://user-images.githubusercontent.com/17680514/177218582-968926e3-1c2f-4fde-a500-1b2790733cba.png)
![image](https://user-images.githubusercontent.com/17680514/177218599-33e83750-edc3-4d6a-a745-10456602fef1.png)

4. Click on the MS Stroe installer:
![image](https://user-images.githubusercontent.com/17680514/177218629-5dfbab2b-3480-4b54-aed0-f3c692688bf7.png)
![image](https://user-images.githubusercontent.com/17680514/177218656-2aa4f5f6-a027-4fb7-b2ea-346725fb6b94.png)


After that, you successfully installed the Microsoft Store test version.
If it works as expected, please let me know.



In addition, here is the test version of the regular installer:

[WindowTop 5.14.0-beta2 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/9042104/WindowTop.5.14.0-beta2.-.setup.exe.zip)

**Comment by gileli121** [comment]
# v5.14.0-beta3

* Fixed small issue with white toolbar themes that the "Requires elevated privileges" text is white (while the theme background is white..)
* Fixed a small regression bug that sometimes the app ignores some windows

## Download installer version
[WindowTop 5.14.0-beta3 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/9043667/WindowTop.5.14.0-beta3.-.setup.exe.zip)

## Download store version
[UWP_PackagingProject_5.14.0.0_Test.zip](https://github.com/BiGilSoft/WindowTop/files/9043694/UWP_PackagingProject_5.14.0.0_Test.zip)

**Comment by gileli121** [comment]
# v5.14.0-beta4

* Fixed regression that dragging to Anchors while the app running as Admin did not work

## Download installer version
[WindowTop 5.14.0-beta4 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/9043770/WindowTop.5.14.0-beta4.-.setup.exe.zip)

## Download store version
[UWP_PackagingProject_5.14.0.0_Test.zip](https://github.com/BiGilSoft/WindowTop/files/9043805/UWP_PackagingProject_5.14.0.0_Test.zip)

**Comment by gileli121** [comment]
After more testing, I did a few more small hotfixes.
Released in v5.14.0
https://github.com/BiGilSoft/WindowTop/releases/tag/v5.14.0
