### ISSUE TITLE
Integrate with minimize button not working with electron windows.

### ISSUE THREAD

**Issue by rp1231** [BiGilSoft/WindowTop#245]
The integrate with minimize button is not working on some windows.
The notable ones are electron apps like slack, discord and vscode.
It's also not working on the windowtop settings app window,
Is windowtop built with electron?

**Comment by gileli121** [comment]
@rp1231 
Windows 11 has snap layouts work with these windows?

Read more about it here
https://thewincentral.com/windows-11-has-snap-layouts-with-3-columns-for-large-displays-improved-docking-multiple-monitor-experience/?amp

And no, WindowTop not built with electron.
"electron" seems to solve the need for cross platform support for UI but all the magic that WindowTop does is too advanced and complicated for making cross platform code.. it built with C# and small part of it built with C++

**Comment by rp1231** [comment]
No, snap layouts does not work with these electron windows.....
But it's strange how it doesn't work with the windowtop settings window....
Especially since it's a native app.
![WindowTop_BwMtUCuuaI](https://user-images.githubusercontent.com/47380919/178436841-d9b2496c-bac3-432e-bc40-517e5f10eb6e.png)
This is a screenshot of the settings window with the "integrate with minimize" option turned on.

**Comment by rp1231** [comment]
> I am not going to share with you my secrets if this is what you asking for. I know that you want this feature in PowerToys but I am not going to help in that in any way

I think you are misunderstanding me, 
I'm not trying to get secrets out of you.
I'm not a programmer, I'm just a power user with a casual interest in software, so it was just a general thing I said.

All I'm looking for is an always on top app that has all the features I need and works on all windows.

The reason I posted this issue is that this software is very close to having all the features I want except for working on all the windows in the same way.

If I can find one software that works on all windows I can end my search.

**Comment by gileli121** [comment]
@rp1231 
Sorry for misunderstanding you.
So what is missing?
You want it to work for any window? That's it?

In such case, I can't deliver such level of functionality.
Even the OS can't in this case

So you want that it will not show even the arrow in case that it failed to detect the minimize button (and you will use hotkey instead? 

If anything else is missing let me know.
My goal is to build the best window manager app :)

**Comment by gileli121** [comment]
@rp1231 
Ok
You have a valid point.

One way around it is to configure the arrow to show on the right side (instead of center) of the window by default. 

This way, you always find the trigger where the minimize button is located so even if you don't remember, you anyway should move the mouse to the minimize button.

Maybe it help

**Comment by gileli121** [comment]
@rp1231 
You know what, if "electron" windows are very common, i can write a specific detection method for these windows..

In all cases that it didn't work, it was another electron window?

With how many windows you tried it?

**Comment by rp1231** [comment]
> One way around it is to configure the arrow to show on the right side (instead of center) of the window by default.
> 
> This way, you always find the trigger where the minimize button is located so even if you don't remember, you anyway should move the mouse to the minimize button.

Yep this is what I'm using now.
