### ISSUE TITLE
[Shrink/PiP + Mouse Interact] - Implement feature to show where exactly is the mouse in the bigger preview

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#249]
Here are some very first recordings of this implementation

https://user-images.githubusercontent.com/17680514/179103970-c8fe75b8-0535-48c5-993e-3d9899b3242a.mp4

You get the idea.
But instead of a red box, it will show the mouse cursor

**Comment by gileli121** [comment]
After a few hours:

https://user-images.githubusercontent.com/17680514/179129402-b87446e6-c9e4-4200-b5bf-01acd02ca849.mp4

**Comment by gileli121** [comment]
v5.16.0-beta1
[WindowTop 5.16.0-beta1 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/9117137/WindowTop.5.16.0-beta1.-.setup.exe.zip)

**Comment by Mystqr4** [comment]
Mouse preview on hover still not working on 5.1.6.beta 2

**Comment by gileli121** [comment]
@Mystqr4 
We will do the regular process I do with most of the users.
You will send me the settings file and using your settings I should reproduce the issue in most cases (unless there is something outside like system configuration)

Please do the following:
1. Go to: `%appdata%/windowtop`
![image](https://user-images.githubusercontent.com/17680514/179210981-5178fd41-b173-4c86-b83e-9a9704a4b4c7.png)
2. Send me these files to email `gileli121@gmail.com`
![image](https://user-images.githubusercontent.com/17680514/179211109-97c6f632-ac07-4400-88a6-f060ab4eb564.png)

I am asking to send it in email in private because the settings contain the activation key and it should not be public.

**Comment by Mystqr4** [comment]
edited my post a few moments after you replied.

I will email you the files in a few moments

**Comment by gileli121** [comment]
@Mystqr4 
I think that I reproduced it.
If you will resize the shrink box/ pip window to smaller, it will work, right?

Seems that you changed the configuration here:
![image](https://user-images.githubusercontent.com/17680514/179213228-e6f7c583-87e7-4cf5-b0bb-751df7aec85d.png)

this is while you did not change this option:
![image](https://user-images.githubusercontent.com/17680514/179213477-4c8c087d-37ac-4a70-96fe-4fcf98c573ee.png)

What it means is that the bigger preview will show up when the size of the PiP window is 120dp or below.
But in the first configuration, you set the default size to 158dp so it will not show the bigger preview from the start.
You need that second configuration will also be 158dp or higher.

May I ask how do you think to call these options in case their meaning is not clear?

About the other issue that it goes out of the screen, I fixed it and also some other issues.

Please try beta 3
[WindowTop 5.16.0-beta3 - setup.zip](https://github.com/BiGilSoft/WindowTop/files/9120439/WindowTop.5.16.0-beta3.-.setup.zip)

Thank you.

**Comment by gileli121** [comment]
@Mystqr4 
Great.
Thanks for the feedback.
So now everything is ok also with this new feature?
May I ask how you write the text of the note?

**Comment by Mystqr4** [comment]
Great work!
It looks like everything is working as it should as far as I can tell.
The new feature seems to be refined and working well also.

I don't know, maybe something like:
WARNING! Please make adjustments to the maximum shrink box size to compliment the "Default Shrink box size" to avoid issues. 

Or

WARNING! Please make adjustments to the maximum shrink box size to compliment the current settings.

**Comment by gileli121** [comment]
Thank you for your efforts in testing the new functionality!
OK, thanks for the feedback. I will add this small improvement in the settings in the final v5.16 release :)

**Comment by Mystqr4** [comment]
> Thank you for your efforts in testing the new functionality! OK, thanks for the feedback. I will add this small improvement in the settings in the final v5.16 release :)

Thanks for the development efforts and implementing so many great features. I will keep testing this software and provide as much feedback as possible where I can to help things along.

**Comment by gileli121** [comment]
@Mystqr4 
Thank you! 
After more thinking about it, in some cases, I did not like the way that the bigger preview was located and when it overlaps the smaller preview and moves with my mouse.

I decided to change a little how the position is calculated. 
Now when INTERACT mode is enabled, the bigger preview will not move and be located as shown here:

https://user-images.githubusercontent.com/17680514/179383990-359ea260-1701-4240-8894-a4cf53f7e4d5.mp4

The cloned mouse pointer was fixed a little. Now it will not look too upscaled
https://user-images.githubusercontent.com/17680514/179384001-95f2a603-34ef-4cd5-966f-b35a86b89f25.mp4

I am almost finished. In the next beta release, I plan to call this "Read mode" under the INTERACT settings and you will have the option to disable/enable it by default.

Here is beta 4 release:
[WindowTop 5.16.0-beta4 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/9127035/WindowTop.5.16.0-beta4.-.setup.exe.zip)

**Comment by Mystqr4** [comment]
Nice update! It's working pretty great and a lot better imho. The only thing that I could maybe add would be if the preview could be made to maybe not cover the taskbar.
Working pretty great!

I have however noticed that when you shrink notepad.exe and enable interact mode it will be impossible to move the window as it will just begin to highlight the text instead, once interact mode is deselected you can move the window around manually again. This is the only one that I have noticed it doing it with so far.

**Comment by gileli121** [comment]
@Mystqr4 
Great to hear!
About the dragging issue, you should be able to drag it by the title bar if you did not disable it in the settings:
![shrink_drag](https://user-images.githubusercontent.com/17680514/179414438-5c2ac260-7986-47ed-b645-b0e8bba3411f.gif)

**Comment by Mystqr4** [comment]
Oh, I did disable that option in the settings and might look at putting that back on perhaps. Coincidentally I had no problems moving notepad++ (which you're using in the example) without the need for extra title bar.

**Comment by gileli121** [comment]
@Mystqr4 
Released in v5.16
https://github.com/BiGilSoft/WindowTop/releases/tag/v5.16.0

**Comment by Mystqr4** [comment]
Thank you.
I am currently testing this version.
I have noticed that my toolbar still says shrink rather than PiP but that doesn't bother me at all but I thought I would mention it. It could be a consequence of me being on a beta release prior.

I had to laugh because the in build update check didn't tell me there was a new release again so I just manually updated.

**Comment by gileli121** [comment]
It is a known issue. These beta builds are also v16.0 so they can't trigger the update notification

**Comment by Mystqr4** [comment]
> It is a known issue. These beta builds are also v16.0 so they can't trigger the update notification

Understood. Makes perfect sense now.

Just for consistency is the "Shrink" to "PiP" term going to be present throughout the settings and examples also. I'd imagine it would less confusing for a new user to see the term Shrink in some places and PiP in others.

I have noticed a few other things but I should probably make another post for those.

**Comment by gileli121** [comment]
@Mystqr4 
In the last update that was released a few weeks ago, I renamed "Shrink" to "PiP" in all areas
