### ISSUE TITLE
Is this program not possible with League of Legends?

### ISSUE THREAD

**Issue by Atormsu** [BiGilSoft/WindowTop#252]
I am basically trying to make it where I can play Runelite, and League of Legends with Runelite on League of Legends screen. (That is possible)

However when I load into game all the keybinds stop working :( I really want to buy this program ,but i'm on trial.... 
Is it not possible?

Have a good day

Sincerely,

Atormsu

**Comment by Atormsu** [comment]
It works for call of duty, just not working for league of legends?
Maybe its the anticheat?

**Comment by gileli121** [comment]
@Atormsu 
Hi, what do you mean by saying "all the keybinds stop working"?
Do you mean that hotkeys stop working when you are in the game?

**Comment by Atormsu** [comment]
Yeah the hot keys will not register from windowtop, however when playing Call of Duty Cold War it still works. I'm beginning to think riot games anti cheat might be interfering not sure though. Unless I just don't understand what I'm doing.

When I'm on call of duty, I can put click through on it and playing oldschool runescape, and when I'm done I disable it and than play call of duty. (This doesn't work for league of legends though unless I turn it into window and hit f8 to get the red border and put my mouse on the edge of the window, which is really hard to do when playing that game. 

Works fine for cold war though. I might just not be doing it right. Not sure.

**Comment by gileli121** [comment]
@Atormsu 
It may be related to the fullscreen mode of the game.
Please check if you can change the fullscreen mode to Borderless.

Usually, you can set it directly in the game resolution settings.
You should see the "Borderless" option somewhere there.

If you did not find such an option, maybe this is worth checking:
https://github.com/Codeusa/Borderless-Gaming/releases

I found it just now. Seems that this app can force the game to run in Borderless mode.

Once the game runs in Borderless mode, click-through should work.

**Comment by Atormsu** [comment]
I already had borderless. I'm beginning to think for that specific game it's not possible?

**Comment by Atormsu** [comment]
Even the normal client won't work. I'm beginning to think riot games prevents that

**Comment by gileli121** [comment]
In such a case I have nothing to do.
But if it works with another app, then please let me know because if yes, I will mark this ticket as a bug.

**Comment by Atormsu** [comment]
It works with other apps, but league of legends is preventing it from working in game or just the normal client. 

So yeah I think its a bug

**Comment by gileli121** [comment]
@Atormsu 
With what app for example it works? What is the app's name, and what exactly do you do with the app?
