### ISSUE TITLE
Transparency mode dont load images correctly

### ISSUE THREAD

**Issue by Nixye** [BiGilSoft/WindowTop#253]
Transparency mode crash images and don't work propertly with apps, example: word chrome and discord;

![image](https://user-images.githubusercontent.com/6026540/183274731-c9ad7b5d-e058-4666-9bbf-7a13ac4923b5.png)

**Comment by gileli121** [comment]
@Nixye 
Thanks for the report.
It is a known issue.

Because this feature is barely used by users and is unstable and hard to develop I am considering a long time to remove it.
