### ISSUE TITLE
Window position in maximized state when dark mode is on

### ISSUE THREAD

**Issue by vjalle** [BiGilSoft/WindowTop#256]
I only enabled the dark mode setting, everything else disabled. Toolbar is also disabled, dark mode can be enabled with a hotkey. The problem:
When dark mode is disabled, windows can be maximized properly. Enabling dark mode in maximized state also works properly.
However, if the dark mode is already enabled for a window, and it's maximized, the window is offset from the top left corner:
![image](https://user-images.githubusercontent.com/79142437/189834128-a2f3f361-7064-4b1b-a384-f782645699d2.png)
Note the white frame around the dark window. It should not be there, and it's not there if the window is maximized in normal mode and only then switched to dark. Even worse, to click a GUI element, you have to click a bit above it. Mouse believes that the GUI is in the correct location, does not take into consideration the offset introduced by WindowTop.
Furthermore, there is quite some flickering when moving/resizing a dark mode window. Some apps, including Outlook, flicker even without resizing the window.
I'm using it on a Lenovo X1. Only integrated graphics so acceleration is not enabled in WindowTop (Btw, when enabled it stops working, window colors are not changed anymore).

Update: if a "darkified" window is maximized, it's offset from the top left corner. However, simply pressing the dark mode hotkey twice (disabling and re-enabling the dark mode) temporarily fixes the issue.

**Comment by gileli121** [comment]
@vjalle 
Thank you for the report.
I will work on fixing this bug, but it will take some time because it is hard to fix.

**Comment by gileli121** [comment]
@vjalle 
I will start to work on it today.
See also https://github.com/BiGilSoft/WindowTop/issues/105
I found a perfect way to improve the rendering performances and save a lot of battery power when the effect is enabled!

You will soon get a good update for the dark mode feature, and this is thanks to the user's support (especially by purchasing the app)

**Comment by gileli121** [comment]
After investigation, the regression bug is the result of the bugfix #225

**Comment by gileli121** [comment]
@vjalle 
Please try this version:
https://github.com/BiGilSoft/WindowTop/issues/264#issuecomment-1272529820

**Comment by gileli121** [comment]
Please try this version
https://github.com/BiGilSoft/WindowTop/releases/tag/v5.19.0
If you get the issue again, please reopen/report it here
