### ISSUE TITLE
When closing windows in dark mode, an empty frame is left on the screen that cannot be moved or closed.

### ISSUE THREAD

**Issue by vjalle** [BiGilSoft/WindowTop#257]
Please see the screenshot:
![image](https://user-images.githubusercontent.com/79142437/189835896-a45d5b3d-feef-4856-b687-6a95b50a0857.png)
The issue is 100% reproducible with Outlook in Office365, happens all the time when closing message windows. It occasionally happens with other windows, too.
When closing the parent application, the ghost windows also disappear.

**Comment by gileli121** [comment]
@vjalle 
Thanks for the report.
This should be easier to fix.

I will work on fixing this when I work on this feature.

**Comment by gileli121** [comment]
@vjalle 
Please try this version:
https://github.com/BiGilSoft/WindowTop/issues/264#issuecomment-1272529820

**Comment by gileli121** [comment]
@vjalle 
Please try this version:
https://github.com/BiGilSoft/WindowTop/issues/264#issuecomment-1272529820

**Comment by gileli121** [comment]
Please try this version
https://github.com/BiGilSoft/WindowTop/releases/tag/v5.19.0
If you get the issue again, please reopen/report here
