### ISSUE TITLE
"Disable when Game Mode detected" setting does the opposite

### ISSUE THREAD

**Issue by still-dreaming-1** [BiGilSoft/WindowTop#268]
On my Windows 10 computer, I always have Game Mode on. I was working through some issues I was having in WindowTop, and noticed the setting for "Disable when Game Mode detected" was already on. I turned it off, wondering if this would help. Then WindowTop completely stopped working. If I hover at the top of a window, the green drop down options don't appear. I turned this setting on again, which should cause WindowTop to be disabled if game mode is on (which it is), and then the WindowTop menus started appearing again. I checked, and I do still have Game Mode on. So the setting seems to do the opposite of what it should for me.

**Comment by gileli121** [comment]
@still-dreaming-1 
Thank you for the report.
This issue was just reported a few days ago by another user.
I will work on a fix for the next version.

**Comment by gileli121** [comment]
Fixed
[WindowTop 5.19.2-beta2 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/10418579/WindowTop.5.19.2-beta2.-.setup.exe.zip)

**Comment by gileli121** [comment]
Released
