### ISSUE TITLE
[Toolbar] add time before showing toolbar

### ISSUE THREAD

**Issue by cleuton4k** [BiGilSoft/WindowTop#269]
add time before showing toolbar when "integrate in minimize button" function is activated. add time between 1 and 5 seconds.

**Comment by gileli121** [comment]
@cleuton4k  I will probably add it as part of https://github.com/BiGilSoft/WindowTop/issues/282

**Comment by gileli121** [comment]
@cleuton4k 
Please check the version from here:
https://github.com/BiGilSoft/WindowTop/issues/282#issuecomment-1399239019

**Comment by gileli121** [comment]
Released in 5.19.2
