### ISSUE TITLE
Save Window Config / Whitelist programs bug

### ISSUE THREAD

**Issue by richardlwood** [BiGilSoft/WindowTop#275]
The instructions are not clear but does "Save Window Config" feature == "Whitelist Programs"?

Bug 1:
Setting a particular window to use opacity.
Close that program & re-open.
Opacity previously set is not applied again.

Bug 2:
Select "Whitelist Programs".
Toolbar cannot now be accessed from any programs.

Issue 1:
The UI elements are ugly - text is twice the size every other menu uses, why?

The menu options or rather their description is very unclear - I want a simple description of what options do, not animated GIFs showing something happening, especially when that something isn't clear.

I would suggest concentrating on the basic functionality and UI experience so it's good and stable and then work on the other features.

(coming from a freeware / shareware / commercial dev for 30+ years)

**Comment by gileli121** [comment]
@richardlwood 
Can I contact you in private?
I can send you the translation file that also contains English.
If you want, you can edit the descriptions in the translation file so they will be better.

**Comment by gileli121** [comment]
@richardlwood 
Please check the version from here:
https://github.com/BiGilSoft/WindowTop/issues/282#issuecomment-1399244997

Thank you

**Comment by gileli121** [comment]
Released in 5.19.2
