### ISSUE TITLE
In Dark mode Autohotkey shortcuts don't respond. 

### ISSUE THREAD

**Issue by DavidHJong** [BiGilSoft/WindowTop#276]
Windows 10 19045.2251
Autohotkey 1.1.34.04
Windowtop 5.19.1.0

When I enable Dark mode for Excel, the autohotkey shortcutes in that window don't work. 
A example script: 
```
#ifwinactive ahk_exe excel.exe
![::send, ^c    ; for copy
!]::send, ^v    ; for paste
```

**Comment by gileli121** [comment]
@DavidHJong 
Was the issue fixed for you via Autohotkey?
I am asking in case you found a workaround for the problem.

**Comment by gileli121** [comment]
Closed due to inactivity
