### ISSUE TITLE
[Request] Ability to set a range of "Set Dark" function

### ISSUE THREAD

**Issue by frozentwist9123492** [BiGilSoft/WindowTop#5]
First of all, I wanted to say thanks for creating this beautiful software. My words can never be able to describe how grateful I am to find your software. It's just that I have a little problem with it. The "set dark" function keeps tampering my already dark Windows environment. Is there any sort of a way for me to set a specific range of which the app can invert the color? Thanks in advance.

**Comment by gileli121** [comment]
Thanks for the great commant and nice to hear that you like the product.

I will consider your request.
If there are more people that want this request, please comment here.

**Comment by zelch** [comment]
I have a somewhat similar request, well, two actually, but related.

First, would it be possible to have a setting so setting dark on a fullscreen application doesn't invert the (already dark) bottom bar?

And second, and far more complicated from a UI perspective, would it be possible to set an area of a window to either be inverted or not, for the annoying applications that have both light and dark UI elements?

**Comment by gileli121** [comment]
I plan to redevelop the dark mode anyway to improve it on 4K resolution.
You want to control how much the window will be dark right?

**Comment by zelch** [comment]
Correct.  In my specific use case, the application has a left side control bar which is dark, but everything else is bright.

**Comment by gileli121** [comment]
The requests here are too complex to develop and not worth the effort.
In addition, there are dark-mode plugins for chrome that maybe can give you the same needs.

Closing this issue.
