### ISSUE TITLE
Keep focus on a primary window when you click a transparent, pinned window (Enhancement)

### ISSUE THREAD

**Issue by williamwilliamwilliam** [BiGilSoft/WindowTop#51]
I have a use case where I have a window pinned on top with with opacity+clickthrough. That small window contains a few clickable buttons. I work on a primary window underneath that window. 

I'd like to be able to click those transparent buttons without losing focus (or maybe only momentarily lose focus) of my primary window. Right now I have to alt-tab or click on the primary window to regain focus before I can start typing.

Would it be possible to set a primary window that receives focus immediately after I click anywhere in that pinned, transparent window?

**Comment by gileli121** [comment]
Hi, 
Sorry for the late reply.
I think that it is impossible (at least for me) to understand your request without a real example.

Please provide a description that includes what is exactly "small window" - what exactly software it is.
and what software is the primary window.

It will be also better if the description will include screenshots of your use-case with these programs

**Comment by gileli121** [comment]
According to the description, it sounds like a bug.
Maybe it fixed in v5.

Can you check it and let me know?
