### ISSUE TITLE
[Request] windows size and position

### ISSUE THREAD

**Issue by randaz81** [BiGilSoft/WindowTop#56]
I would like to store/recall the size and position of one or multiple windows.
Is there any program to add this functionality to WindowTop?

**Comment by gileli121** [comment]
Thanks for your suggestion.
I will consider it.
It will take a while until I will release new version because I will rewrite it in C# so for now it is not going to happen soon.

**Comment by gileli121** [comment]
@randaz81 
I want to add this functionality.
It should be easy to develop.

But I don't know how it should look in the UI
Currently, we have these options:
![image](https://user-images.githubusercontent.com/17680514/116963806-875b5d00-acb2-11eb-93d0-b22b03eb86ab.png)


But "Save window configuration" is only about what features to enable by default (such as opacity, set-top, dark-mode).
I don't want it to be also about window size and position...

So we may have to add another option called 
"Save window size and position"
"Delete window size and position"
(Not sure that this is the best way I should call it)

But then maybe it will look complex and unclear..
What do you think?
Do you have another idea how to develop it in the UI level?

**Comment by gileli121** [comment]
@randaz81 
There is no need for this feature in Windows 11.
I think that it is not worth it.

I am closing this request for now.
