### ISSUE TITLE
Is it possible for the Glass detection to be cleaner?

### ISSUE THREAD

**Issue by Jonius7** [BiGilSoft/WindowTop#59]
I've been playing around with making dark apps like Steam use transparent glass, at least for the sidebar.

It seems that WindowTop's glass detection isn't that clean and leaves many white pixels and noise on the borders of elements.

![2021-03-01 14_19_17-Greenshot](https://user-images.githubusercontent.com/1049415/109451657-a31b6a80-7a99-11eb-90bf-1cd4b70c1f69.png)

Are you able to improve on this? If so, it would be possible to use WindowTop to make a theme someone has been showcasing: https://www.reddit.com/r/Steam/comments/k3jj7h/based_on_your_feedback_i_redesigned_steam_again/

Their main request was making the sidebar partially transparent/see-through, and this is usually not possible with most applications.

**Comment by gileli121** [comment]
Hi,
It was done in version v5 that was not released yet and under development.
In version 5, I rewrote this glass effect detection algorithm and I solved the problem you show.
The whole program is rewritten in C# and will include major improvements for the UI.

The project to rewrite the software in C# and rewrite the glass effect & dark-mode effects took until now 4 months and I estimate that it will take more 1.5 months until we have the first version of it.
Until then, you will have to wait.

You can see few screenshots here:
https://github.com/gileli121/WindowTop/issues/55

**Comment by gileli121** [comment]
Hi, In version 5 that still under development the glass algorithm was improved and I fixed the rendering issues.
But I tested it and found that unfortunately, it will not work well with steam theme unless you can change the theme of steam to something without this:
![image](https://user-images.githubusercontent.com/17680514/109609113-9186a100-7b33-11eb-8f15-9f2adb375ef0.png)
and this
![image](https://user-images.githubusercontent.com/17680514/109609208-b1b66000-7b33-11eb-880b-a63836893fe0.png)

The problem with these is that the background is not one color. 
If you can change steam backgrounds to be with one color then the glass detection algorithm will work perfectly

**Comment by Jonius7** [comment]
> If you can change steam backgrounds to be with one color then the glass detection algorithm will work perfectly
Yes, this is possible and fairly simple to do.

Good to hear, I await the version 5 of Windowtop!

**Comment by gileli121** [comment]
Great

I used this algorithm to write a plugin for JetBrains IDEs
I modified the theme to be with very basic backgrounds (like one color for each background).
You can see the result here:
http://glass-code.com/

So this is how it should work if the theme is simple as I said

**Comment by gileli121** [comment]
@Jonius7 
Please try this beta release of version 5 and let me know how it works
https://github.com/gileli121/WindowTop/releases/tag/v5.x.x

Enjoy!

**Comment by gileli121** [comment]
@Jonius7 
I found a way to improve it so that it will work perfect.
See:
Dark/Glass Modes - Improve rendering performance by removing the need of image & text recognition algorithms #105

Issue reopened

**Comment by gileli121** [comment]
Closed for inactivity, and it may be improved already.
