### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by EienFr** [BiGilSoft/WindowTop#65]
Hi,

I would like to set up even more modern icons. I find the classic theme prettier than the modernui.

I imagined for example icons like that.

![prop](https://user-images.githubusercontent.com/46239183/111910323-332d4e00-8a61-11eb-858c-5a75598c1968.jpg)

What do you think ?

**Comment by gileli121** [comment]
This is very nice!
First I need to implement an option to change the icons.

About what you said that the classic icons look prettier - I can't agree because there is a survey that proves that most people prefer the new icons.

But the icons you gave look very professional and I can see why I and other people can like them also.
Thanks

**Comment by EienFr** [comment]
Hey,

Thanks for your quick reply !

I didn't know there had been a poll. After all the perception is always very personal :)

I don't know if it's difficult for you to implement new icons but I can make you several sets that you can integrate only for premium members for example.

I already have several ideas in flat design, colored, unicolour, bi-color, etc.

I can help you by translating this tool in French.

Feel free to contact me :)

**Comment by gileli121** [comment]
@EienFr 
Please contact me via gileli121@gmail.com

**Comment by gileli121** [comment]
@EienFr 
Hi, I am working on it now as part of branch `v5.5`

**Comment by gileli121** [comment]
@EienFr 
Hi, I am working on it now as part of branch `v5.5`

**Comment by gileli121** [comment]
@EienFr 
First icons implemented:
![FluentBlueTheme_dev_demo1](https://user-images.githubusercontent.com/17680514/132252965-da5708c0-db80-4dc3-ac1e-e658c048cf1d.gif)

**Comment by gileli121** [comment]
Fluent White Gray:

![Uploading FluentWhiteGray_dev_demo1.gif…]()

**Comment by gileli121** [comment]
Fluent Gray Full:
![FluentGrayFull_dev_demo1](https://user-images.githubusercontent.com/17680514/132257138-7f080c90-a6b3-4596-be66-24b7199c88cf.gif)

**Comment by gileli121** [comment]
Fluent Blue Pink:
![FluentBluePink_dev_demo1](https://user-images.githubusercontent.com/17680514/132260393-0d2dfc49-c414-4043-9c20-6f6593476e96.gif)

**Comment by gileli121** [comment]
Fluent Dark Border:
![FluentDarkBorder_dev_demo1](https://user-images.githubusercontent.com/17680514/132261004-bf8321b4-3d48-4a25-a329-f7c92a2b20fd.gif)

**Comment by EienFr** [comment]
Wow nice ! Seems really cool, I can't wait to test it :)

**Comment by gileli121** [comment]
@EienFr 
I finished to implemented it.
In settings you should see the option to change toolbar theme
![image](https://user-images.githubusercontent.com/17680514/132301947-c7617fd2-0d3b-4a95-8847-1b552fa197aa.png)

Please test this build:
[WindowTop Build 07-09-21_1.zip](https://github.com/BiGilSoft/WindowTop/files/7119720/WindowTop.Build.07-09-21_1.zip)

Note that for now there is one issue with this icon:
![image](https://user-images.githubusercontent.com/17680514/132302476-ddab0114-1aab-4dc3-a423-e8f722138822.png)

It will help if you send PSD file with this icon also.
Thanks

**Comment by EienFr** [comment]
Works perfect. Hum, normally this icon is on the PSD file. I'll send it to you.

**Comment by gileli121** [comment]
@EienFr 
Thanks, 
I fixed now the interact icon in the other themes.

Here is new build with the small fix:
[WindowTop Build 07-09-21_2.zip](https://github.com/BiGilSoft/WindowTop/files/7120365/WindowTop.Build.07-09-21_2.zip)

**Comment by gileli121** [comment]
Released in v5.5
