### ISSUE TITLE
Request: shortcut menu appear on initiated screen on any Scale value

### ISSUE THREAD

**Issue by samkatakouzinos** [BiGilSoft/WindowTop#69]
**Issue:** Taskbar shortcut appears on another screen if Scale not 100%. 
**Request:** shortcut menu appear on initiated screen on any Scale value. 

Triple screen horizontally with all 3 screen being 3840x2160 with Scale = 200%. 
Left or right clicking Taskbar icon on middle screen makes shortcut menu appear on right screen. 
With only middle screen changed to Scale 100% shortcut menu appears on middle screen, correctly.

**Comment by gileli121** [comment]
@samkatakouzinos 
May be it is the same as #68 ?

**Comment by samkatakouzinos** [comment]
My issue is with windows scaling <> 100% causing shortcut popup on another screen. 
As long as your fix there works for issue here then yes maybe the same.

**Comment by gileli121** [comment]
@samkatakouzinos 

The DPI issues should be fixed now in v5.1.4
Please download it and let me know if it fixed for you

**Comment by samkatakouzinos** [comment]
Almost fixed. 

Starting with my default of 3840x2160, 200%;
Success with scale from 100 through 300
Fail at scale 350

My choices of scale on my system range from 100 to 350

**Comment by gileli121** [comment]
OK, thanks for the report!
Any idea why anyone will want to use cale 350?

**Comment by samkatakouzinos** [comment]
> Any idea why anyone will want to use scale 350?
A more applicable question; 
What range of screen resolutions, range of scales and end cases have you limited testjng to so far?

**Comment by gileli121** [comment]
I tested it on 1920x1080
With scaling up to 175% after the fix

**Comment by samkatakouzinos** [comment]
I have 3840x2160 triple screens with scaling options up to 350% and resolutions down to 800x600. 
Happy to test updates with my setup.

**Comment by gileli121** [comment]
Is this is an issue for you?
Do you use scaling 350%?
If not I will consider to keep this open for now and handle it later when someone will also report about it

**Comment by samkatakouzinos** [comment]
My default is 3840x2160 @ 200%
I don't use 350% often but will go to 300% for some work types.

**Comment by gileli121** [comment]
I will keep this open.
If more users report about it I will try to fix this issue

**Comment by gileli121** [comment]
No more users have reported about it since then.
Closed for inactivity and low priority.
