### ISSUE TITLE
Logic of tray icon: double left click to open the setting GUI

### ISSUE THREAD

**Issue by WZ-Tong** [BiGilSoft/WindowTop#81]
That makes sense, right click for toolbar/setting, left click to open the main UI

**Comment by gileli121** [comment]
@WZ-Tong 
Is this is common in a lot of programs?

I even used to do left-click to open the tray menu options

**Comment by WZ-Tong** [comment]
I think so (as a Chinese), but it dosen't matter (because after setted up, I never open the main UI again).

This issue is just a small suggestion and it isn't a big matter.

Thanks for paying attention
