### ISSUE TITLE
Add WindowTop to chocolatey.org repository

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#89]
This was requested by few users

**Comment by gileli121** [comment]
![image](https://user-images.githubusercontent.com/17680514/123512036-c17f2480-d68d-11eb-8eab-d39a8c8ef613.png)

**Comment by Gitoffthelawn** [comment]
Just curious... what took place after you tried to submit this to them?

**Comment by gileli121** [comment]
They had a requirement to modify the installer so it will able to close the app instead of telling the user to do it.
I suggested that the script will tell the user to do it after he typed to install command. He did not accept it.
It is hard to make a better installer and does not worth the effort.
Especially because it is distributed in the store and with winget.
